# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  hevea-benchmarks:
    dependencies:
    - base
    - hevea
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: hevea is a new Haskeleton package.
executables:
  hevea:
    dependencies:
    - base
    - hevea
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
# ghc-options: -Wall
github: mrkgnao/hevea
library:
  dependencies:
  - base
  - time
  - template-haskell
  - haskell-src-meta
  - pretty
  - mtl
  source-dirs: library
license: MIT
maintainer: Soham Chowdhury
name: hevea
synopsis: A new Haskeleton package.
tests:
  hevea-test-suite:
    dependencies:
    - base
    - hevea
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
